version: '3'

services:
  postgres-local:
    image: postgres:14.1-alpine3.15
    container_name: postgres-local
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    volumes:
      - ./db/data/:/var/lib/postgresql/data
      - ./db/structure.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "5432:5432"
    restart: always
