version: '3'

services:
  db:
    container_name: db
    build: ./db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    restart: always
    ports:
      - "5432:5432"

  app:
    container_name: app
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - "5500:5500"
      - "5501:5501"
      - "5502:5502"
